In [1]:
import matplotlib
import scipy
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from sklearn.metrics import accuracy_score, confusion_matrix
pd.options.mode.chained_assignment = None 

In [2]:
def parse_data(given_path, file_name):
    metars_path = os.path.join(given_path, file_name)
    metars_data = pd.read_csv(metars_path)
    return metars_data

In [3]:
save_path = os.path.abspath(os.path.join(os.pardir, 'data'))
given_data_1 = parse_data(save_path, 'metars_cache_1.csv')
given_data_2 = parse_data(save_path, 'metars_test_cache.csv')
given_data_3 = parse_data(save_path, 'metars_test2_cache.csv')

# Concatenate all of these DataFrames
given_data = pd.concat([given_data_1, given_data_2, given_data_3])

display(given_data)

raw_text station_id  \
0     KBCT 220253Z 35007KT 10SM VCTS BKN050 22/17 A3...       KBCT   
1     YSNF 220252Z AUTO 09007KT 9999 -SHRA SCT020 SC...       YSNF   
2     YCOM 220252Z AUTO 01013KT 5000 // SCT013 SCT02...       YCOM   
3     PAFM 220252Z AUTO 12003KT 10SM FEW004 SCT015 O...       PAFM   
4     PABV 220252Z AUTO 05003KT 10SM BKN004 02/02 A2...       PABV   
...                                                 ...        ...   
4767  MMGM 222340Z 20008KT 10SM SCT030 BKN120 29/26 ...       MMGM   
4768  MMCV 222340Z 16009KT 10SM BKN250 26/15 A2988 R...       MMCV   
4769  MMCN 222340Z 24005KT 10SM BKN210 29/20 A2973 R...       MMCN   
4770  MMCB 222340Z 00000KT 9SM SCT015 BKN080 BKN250 ...       MMCB   
4771  MMAS 222340Z 19005KT 9SM SCT100 SCT200 22/07 A...       MMAS   

          observation_time  latitude  longitude  temp_c  dewpoint_c  \
0     2022-10-22T02:53:00Z     26.38     -80.10    22.0        17.0   
1     2022-10-22T02:52:00Z    -29.03     167.93    18.0        16.0   
2     2022-10-22T02:52:00Z    -36.30     148.97     NaN         NaN   
3     2022-10-22T02:52:00Z     67.10    -157.85     1.0         0.0   
4     2022-10-22T02:52:00Z     61.42    -149.52     2.0         2.0   
...                    ...       ...        ...     ...         ...   
4767  2022-10-22T23:40:00Z     27.95    -110.92    29.0        26.0   
4768  2022-10-22T23:40:00Z     23.72     -98.97    26.0        15.0   
4769  2022-10-22T23:40:00Z     27.40    -109.83    29.0        20.0   
4770  2022-10-22T23:40:00Z     18.83     -99.27    25.0        19.0   
4771  2022-10-22T23:40:00Z     21.70    -102.32    22.0         7.0   

      wind_dir_degrees  wind_speed_kt  wind_gust_kt  ...  maxT24hr_c  \
0                350.0            7.0           NaN  ...         NaN   
1                 90.0            7.0           NaN  ...         NaN   
2                 10.0           13.0           NaN  ...         NaN   
3                120.0            3.0           NaN  ...         NaN   
4                 50.0            3.0           NaN  ...         NaN   
...                ...            ...           ...  ...         ...   
4767             200.0            8.0           NaN  ...         NaN   
4768             160.0            9.0           NaN  ...         NaN   
4769             240.0            5.0           NaN  ...         NaN   
4770               0.0            0.0           NaN  ...         NaN   
4771             190.0            5.0           NaN  ...         NaN   

      minT24hr_c  precip_in pcp3hr_in pcp6hr_in pcp24hr_in snow_in  \
0            NaN        NaN       NaN       NaN        NaN     NaN   
1            NaN        NaN       NaN       NaN        NaN     NaN   
2            NaN        NaN       NaN       NaN        NaN     NaN   
3            NaN      0.005       NaN       NaN        NaN     NaN   
4            NaN        NaN       NaN       NaN        NaN     NaN   
...          ...        ...       ...       ...        ...     ...   
4767         NaN        NaN       NaN       NaN        NaN     NaN   
4768         NaN        NaN       NaN       NaN        NaN     NaN   
4769         NaN        NaN       NaN       NaN        NaN     NaN   
4770         NaN        NaN       NaN       NaN        NaN     NaN   
4771         NaN        NaN       NaN       NaN        NaN     NaN   

     vert_vis_ft metar_type elevation_m  
0            NaN      METAR         3.0  
1            NaN      SPECI       113.0  
2            NaN      SPECI       930.0  
3            NaN      SPECI        79.0  
4            NaN      SPECI        21.0  
...          ...        ...         ...  
4767         NaN      METAR        13.0  
4768         NaN      METAR       230.0  
4769         NaN      METAR        57.0  
4770         NaN      METAR      1281.0  
4771         NaN      METAR      1866.0  

[14325 rows x 44 columns]

In [4]:
# Do some basic cleaning to get rid of rows that are missing lat/long, since that's the bare minimum we need
cleaned_data = given_data.dropna(axis=0, subset=['latitude', 'longitude'])
cleaned_data = cleaned_data.reset_index(drop=True)

In [5]:
def filter_usa(df: pd.DataFrame) -> pd.DataFrame:
    """Takes in world data and crudely restricts to just lat/long values corresponding to the lower 48"""

    # We'll be using latitude bounds of [24, 49] and longitude bounds of [-125, -67] based on https://www.findlatitudeandlongitude.com/l/Lower+48/4315442/
    return df.loc[(df['latitude'] >= 24) & (df['latitude'] <= 49) & (df['longitude'] >= -125) & (df['longitude'] <= -67)]

# Get a rough estimate of the data corresponding to the US (minus Alaska and Hawaii)
usa_data = filter_usa(cleaned_data)

# Also, because 'Murica, let's change the units from C to F
usa_data['temp_f'] = usa_data['temp_c'].apply(lambda x: (x * (9.0 / 5.0) + 32))
usa_data['dewpoint_f'] = usa_data['dewpoint_c'].apply(lambda x: (x * (9.0 / 5.0) + 32))

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def random_downsample():
    cleaned_usa = usa_data.dropna(axis=0, subset=['temp_c', 'dewpoint_c', 'wind_speed_kt', 'visibility_statute_mi'])
    cleaned_usa = cleaned_usa.reset_index(drop=True)

    print("Number of Rows: ", len(cleaned_usa.index))
    speci_data = cleaned_usa.loc[cleaned_usa['metar_type'] == 'SPECI']
    print("Number of SPECI Rows: ", len(speci_data.index))

    metar_data = cleaned_usa.loc[cleaned_usa['metar_type'] == 'METAR']
    print("Number of METAR Rows: ", len(metar_data.index))
    downsized_metar_data = metar_data.sample(n=len(speci_data.index))

    # Put together the SPECI data and sampled METAR data
    combined_data = pd.concat([speci_data, downsized_metar_data])
    print("Size of Re-Balanced/Sampled Dataset: ", len(combined_data.index))

    inputs = combined_data.loc[:, ['temp_c', 'dewpoint_c', 'wind_speed_kt', 'visibility_statute_mi']]

    outputs = combined_data.loc[:, 'metar_type']

    inputs_train, inputs_test, outputs_train, outputs_test = train_test_split(inputs, outputs, test_size=0.2)
    
    # Scale the inputs metrics
    scaler = StandardScaler()
    scaled_train_arr = scaler.fit_transform(inputs_train)
    scaled_train = pd.DataFrame(data=scaled_train_arr, columns=inputs.columns)
    scaled_test_arr = scaler.fit_transform(inputs_test)
    scaled_test = pd.DataFrame(data=scaled_test_arr, columns=inputs.columns)
    return scaled_train, scaled_test, outputs_train, outputs_test

def pre_smote():
    cleaned_usa = usa_data.dropna(axis=0, subset=['visibility_statute_mi'])
    cleaned_usa = cleaned_usa.reset_index(drop=True)

    print("Number of Rows: ", len(cleaned_usa.index))

    inputs = cleaned_usa.loc[:, ['visibility_statute_mi']]

    outputs = cleaned_usa.loc[:, 'metar_type']

    inputs_train, inputs_test, outputs_train, outputs_test = train_test_split(inputs, outputs, test_size=0.2)

    # Scale the inputs metrics
    scaler = StandardScaler()
    scaled_train_arr = scaler.fit_transform(inputs_train)
    scaled_train = pd.DataFrame(data=scaled_train_arr, columns=inputs.columns)
    scaler = StandardScaler()
    scaled_test_arr = scaler.fit_transform(inputs_test)
    scaled_test = pd.DataFrame(data=scaled_test_arr, columns=inputs.columns)
    return scaled_train, scaled_test, outputs_train, outputs_test


In [224]:
resampled_inputs_train, inputs_test, resampled_outputs_train, outputs_test = random_downsample()

Number of Rows:  6589
Number of SPECI Rows:  633
Number of METAR Rows:  5956
Size of Re-Balanced/Sampled Dataset:  1266


In [7]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy='minority')

inputs_train, inputs_test, outputs_train, outputs_test = pre_smote()

resampled_inputs_train, resampled_outputs_train = sm.fit_resample(inputs_train, outputs_train)

# For some reason, the SMOTE implementation seems to leave the data in an unshuffled state. So I will manually reshuffle
shuffle_order = np.random.permutation(resampled_inputs_train.index)
resampled_inputs_train = resampled_inputs_train.reindex(shuffle_order)
resampled_outputs_train = resampled_outputs_train.reindex(shuffle_order)


display(resampled_inputs_train)
display(resampled_outputs_train)

Number of Rows:  6703


visibility_statute_mi
7937               0.063795
2335               0.063795
6508               0.063795
1202               0.063795
7487               0.063795
...                     ...
1828               0.063795
7942               0.063795
6165               0.063795
4221               0.063795
8154               0.063795

[9698 rows x 1 columns]

7937    SPECI
2335    METAR
6508    SPECI
1202    METAR
7487    SPECI
        ...  
1828    METAR
7942    SPECI
6165    SPECI
4221    METAR
8154    SPECI
Name: metar_type, Length: 9698, dtype: object

In [369]:
from sklearn.linear_model import LogisticRegression

logModel = LogisticRegression()

logModel.fit(resampled_inputs_train, resampled_outputs_train)

pred_output = logModel.predict(inputs_test)

print("Accuracy: ", accuracy_score(outputs_test, pred_output))
print("Confusion Matrix: \n", confusion_matrix(outputs_test, pred_output))

speci_counter = 0
for x in range(len(pred_output)):
    if pred_output[x] == 'SPECI':
        speci_counter += 1

print(speci_counter)

Accuracy:  0.8501118568232662
Confusion Matrix: 
 [[1125   80]
 [ 121   15]]
95


In [378]:
cleaned_usa = usa_data.dropna(axis=0, subset=['visibility_statute_mi'])
cleaned_usa = cleaned_usa.reset_index(drop=True)

print("Number of Rows: ", len(cleaned_usa.index))

inputs = cleaned_usa.loc[:, ['visibility_statute_mi']]

outputs = cleaned_usa.loc[:, 'metar_type']

# Scale the inputs metrics
scaler = StandardScaler()
scaled_inputs_arr = scaler.fit_transform(inputs)
scaled_inputs = pd.DataFrame(data=scaled_inputs_arr, columns=inputs.columns)

from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy='minority')

resampled_inputs, resampled_outputs = sm.fit_resample(inputs, outputs)

# For some reason, the SMOTE implementation seems to leave the data in an unshuffled state. So I will manually reshuffle
shuffle_order = np.random.permutation(resampled_inputs.index)
resampled_inputs = resampled_inputs.reindex(shuffle_order)
resampled_outputs = resampled_outputs.reindex(shuffle_order)

from sklearn.linear_model import LogisticRegression

finalLogModel = LogisticRegression()

finalLogModel.fit(resampled_inputs, resampled_outputs)

import pickle
pickle.dump(finalLogModel, open('model', 'ab'))

Number of Rows:  6703


In [379]:
import pickle
pickle.load(open('model.pickle', 'rb'))

LogisticRegression()

In [371]:
from sklearn.tree import DecisionTreeClassifier

# With this for some reason, only visibility_statute gives decent results. Even including the others drops accuracy down to 0.36

clf = DecisionTreeClassifier(ccp_alpha=0.0001)
clf.fit(resampled_inputs, resampled_outputs)

pred_output = clf.predict(inputs_test)

print("Accuracy: ", accuracy_score(outputs_test, pred_output))
print("Confusion Matrix: \n", confusion_matrix(outputs_test, pred_output))

speci_counter = 0
for x in range(len(pred_output)):
    if pred_output[x] == 'SPECI':
        speci_counter += 1

print(speci_counter)

Accuracy:  0.8583146905294556
Confusion Matrix: 
 [[1138   67]
 [ 123   13]]
80


In [372]:
from sklearn.svm import SVC

svc = SVC(C=0.01)
svc.fit(resampled_inputs, resampled_outputs)

pred_output = svc.predict(inputs_test)

print("Accuracy: ", accuracy_score(outputs_test, pred_output))
print("Confusion Matrix: \n", confusion_matrix(outputs_test, pred_output))

speci_counter = 0
for x in range(len(pred_output)):
    if pred_output[x] == 'SPECI':
        speci_counter += 1

print(speci_counter)

Accuracy:  0.8553318419090231
Confusion Matrix: 
 [[1134   71]
 [ 123   13]]
84
